################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/bsp.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/debug.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_gpio.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_rtc.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_spi.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/main.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/src/mlm32l0xx_hal_msp.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/src/mlm32l0xx_hw.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/src/mlm32l0xx_it.c \
/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/vcom.c 

OBJS += \
./Projects/End_Node/bsp.o \
./Projects/End_Node/debug.o \
./Projects/End_Node/hw_gpio.o \
./Projects/End_Node/hw_rtc.o \
./Projects/End_Node/hw_spi.o \
./Projects/End_Node/main.o \
./Projects/End_Node/mlm32l0xx_hal_msp.o \
./Projects/End_Node/mlm32l0xx_hw.o \
./Projects/End_Node/mlm32l0xx_it.o \
./Projects/End_Node/vcom.o 

C_DEPS += \
./Projects/End_Node/bsp.d \
./Projects/End_Node/debug.d \
./Projects/End_Node/hw_gpio.d \
./Projects/End_Node/hw_rtc.d \
./Projects/End_Node/hw_spi.d \
./Projects/End_Node/main.d \
./Projects/End_Node/mlm32l0xx_hal_msp.d \
./Projects/End_Node/mlm32l0xx_hw.d \
./Projects/End_Node/mlm32l0xx_it.d \
./Projects/End_Node/vcom.d 


# Each subdirectory must supply rules for building sources it contributes
Projects/End_Node/bsp.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/bsp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/debug.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/debug.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_gpio.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_rtc.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_spi.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/hw_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/main.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/mlm32l0xx_hal_msp.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/src/mlm32l0xx_hal_msp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/mlm32l0xx_hw.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/src/mlm32l0xx_hw.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/mlm32l0xx_it.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/src/mlm32l0xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/vcom.o: /media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/src/vcom.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/Core/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Projects/B-L072Z-LRWAN1/Applications/LoRa/End_Node/LoRaWAN/App/inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/CMWX1ZZABZ-0xx" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/CMSIS/Include" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Crypto" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Phy" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Utilities" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Core" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/Common" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/hts221" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps22hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/lps25hb" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/Components/sx1276" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Drivers/BSP/B-L072Z-LRWAN1" -I"/media/mrthanh/DATA/thuc_tap/sw4stm32/STM32CubeExpansion_LRWAN_V1.2.1/Middlewares/Third_Party/LoRaWAN/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


